Fix restricted user AssetEvent bug
openremote/openremote pull request #1020
Opened 2023-03-30 14:57 UTC by richturner

Resolves #969

2023-03-30 15:07 UTC, MartinaeyNL requested changes

2023-03-30 15:07 UTC, MartinaeyNL commented on test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy
> +            def isTirggered = !isSubscription && message.startsWith(TriggeredEventSubscription.MESSAGE_PREFIX)
Minor typo

2023-03-30 15:36 UTC, richturner commented on test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy
> +        def connectionStatus2 = client.getConnectionStatus()
Good spot; doesn't affect the test as the test wouldn't pass if client2 wasn't connected but worth fixing

2023-03-30 15:37 UTC, richturner commented on test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy
> +            def isTirggered = !isSubscription && message.startsWith(TriggeredEventSubscription.MESSAGE_PREFIX)
Another good spot thanks

2023-03-30 15:38 UTC, MartinaeyNL approved these changes

2023-03-31 07:34 UTC, MartinaeyNL approved these changes

2023-03-31 08:14 UTC, merged