Enhancement/data table
openremote/openremote pull request #1105
Opened 2023-08-21 13:07 UTC by NinaBianca

2023-08-28 12:27 UTC, MartinaeyNL requested changes

2023-08-28 12:27 UTC, MartinaeyNL commented on ui/component/or-mwc-components/src/or-mwc-table.ts
> +                                                        ${this.config.multiSelect ? '' : html` @click="${(ev: MouseEvent) => this.dispatchEvent(new OrMwcTableRowClickEvent((this.rows as any[]).indexO
Should the click be removed when `multiSelect` is true?

2023-10-09 12:32 UTC, MartinaeyNL submitted a review, later dismissed

2023-10-10 07:54 UTC, DonWillems commented
- Sort arrow should have app color: --or-icon-fill: var(--or-app-color3);
- Header is clickable: sort class changes, but sorting is not applied. It does work when the text is clicked. Make it so that sorting happens on full header cell click.
- I didn't know how to use the selectedRows, so I could test that with e.g. a button on the page that logs the selected rows. Help!
- What is "columnFilter" in the TableConfig? Doesn't seem to do anything? @MartinaeyNL 
- There is a lost console.log in there
- With multiSelect enabled, the padding on the header cells changes and it doesn't align with the content of the cells anymore.

2023-10-10 09:01 UTC, MartinaeyNL commented
> * What is "columnFilter" in the TableConfig? Doesn't seem to do anything? @MartinaeyNL 

It indeed is unused currently. Was originally added in 2020, so might be removed functionality since then.
Also don't know what it was for unfortunately.

2023-10-12 13:56 UTC, DonWillems approved these changes

2023-10-12 14:46 UTC, merged

2023-10-12 14:46 UTC, MartinaeyNL commented
Merged. Code also looks fine enough to me.