Tunnel is now stopped upon deleting the gateway asset
openremote/openremote pull request #1339
Opened 2024-07-08 14:48 UTC by MartinaeyNL

Fix for issue that the tunnel was not stopped when deleting a gateway asset.
I've added the `stopTunnel()` function within the `requestDisconnect` runnable, so it attempts to disconnect the tunnel.

Haven't done extensive testing (on a deployment for example), but it works fine for me locally.

2024-07-16 12:40 UTC, richturner requested changes

2024-07-16 12:40 UTC, richturner commented on manager/src/main/java/org/openremote/manager/gateway/GatewayService.java
> +            });
This is the wrong place to do this; we want to stop and remove tunnels in the `processGatewayChange` method specifically in the `DELETE` case.

2024-07-19 12:29 UTC, MartinaeyNL commented
Moved the logic to the `DELETE` clause in `processGatewayChange` as requested.
To be clear; I haven't tested this new logic on my machine. Please verify.

2024-07-22 09:35 UTC, richturner approved these changes

2024-07-22 09:36 UTC, merged