[Flow rules] Add historic value, sum, maximum, minimum, average, and median blocks
openremote/openremote pull request #1525
Opened 2024-12-06 17:14 UTC by pankalog

This PR adds several blocks to the flow rules, namely:
	- `HISTORIC_VALUE`,
	- `SUM_PROCESSOR`,
	- `MAX_PROCESSOR`,
	- `MIN_PROCESSOR`,
	- `AVG_PROCESSOR`,
	- `MEDIAN_PROCESSOR`

Main issue was allowing the input of multiple lines into a single socket. After that, some UI changes to allow multiple pickers to be created, along with their styling, using `NodeInternal.BreakType`. Partial support for array types of any primitive type were also added, by adding `_ARRAY` after the data type, and adding that to `NodeDataType`.

2024-12-06 17:15 UTC, pankalog commented
fixes #1488

2024-12-06 17:16 UTC, pankalog commented
TODO: Still need some guidance about tests, and removing `DEBUG_TO_CONSOLE` output block.

2024-12-09 13:27 UTC, wborn commented
I retriggered the build as it seems to fail on the `MQTTClientProtocolTest` which I've also seen failing in other PRs (#1528)

2025-01-20 13:37 UTC, richturner requested changes
Hey,

I see various changes to existing code (styling, files deleted etc.) but I don't know the reason for these, some comments explaining what is being fixed/improved would be helpful.

2025-01-20 17:03 UTC, pankalog commented on ui/component/or-rules/src/flow-viewer/components/internal-picker.ts
> +                return this.getNumberInput(0, 365);
We worked on this with Martin, and since it only makes sense to have a max number of 365 (365 days in a year). This helps with spacing the input field.

2025-01-20 17:06 UTC, pankalog commented on manager/src/main/java/org/openremote/manager/rules/RulesFacts.java
> +
I need this in `FlowResourceImpl` to read `OR_DEV_MODE` that you mentioned below.

2025-01-20 17:07 UTC, pankalog commented on manager/src/main/java/org/openremote/manager/rules/RulesService.java
> +                container
I need this in `FlowResourceImpl` to read `OR_DEV_MODE` that you mentioned below.

2025-01-20 17:29 UTC, pankalog commented on manager/src/main/java/org/openremote/manager/rules/flow/FlowResourceImpl.java
> +        if(MapAccess.getBoolean(container.getConfig(), "OR_DEV_MODE",false)){
I made a getter for `RulesFacts.LOG` for this, is that okay?

2025-01-20 17:37 UTC, pankalog commented on manager/src/main/java/org/openremote/manager/rules/flow/NodeModel.java
I also agree that the return value of `NodeImplementation.execute()` needs a bit more work, but those changes were way too convoluted to perform for now unfortunately.

If you want me to take up that task, we can make a new issue and I'll take it up.

2025-01-20 17:41 UTC, pankalog commented on ui/component/or-rules/src/flow-viewer/components/flow-node.ts
> +            html`<div class="title minimal" ?singlechar="${this.node.displayCharacter!.length === 1}">${String(i18next.t("flow."+this.node.displayCharacter!, this.node.displayCharacter!))}</div>` :
Fixed

2025-01-20 17:41 UTC, pankalog commented on manager/src/main/java/org/openremote/manager/rules/flow/NodeModel.java
> +                System.out.println(new AttributeRef(assetId, attributeName));
Removed all `System.out.println`s from `NodeModel`

2025-01-20 17:42 UTC, pankalog commented on manager/src/main/java/org/openremote/manager/rules/RulesFacts.java
> +
Removed

2025-01-21 08:57 UTC, MartinaeyNL commented on ui/component/or-rules/src/flow-viewer/components/internal-picker.ts
> +                return this.getNumberInput(0, 365);
We indeed had a conversation about this.
However, I mentioned this should only be applied to your "date" field, instead of all numbers in FLOW rules.

2025-01-21 08:59 UTC, MartinaeyNL requested changes
Wanted to address an specific issue on the `internal-picker` file.
Don't see this as a full code review.

2025-01-21 08:59 UTC, MartinaeyNL commented on ui/component/or-rules/src/flow-viewer/components/internal-picker.ts
> +                return this.getNumberInput(0, 365);
This minimum of 0, and maximum of 365, should only be applied to your "date" field.
Now it applies to ALL numbers in the FLOW rules.

2025-01-21 11:08 UTC, richturner commented on manager/src/main/java/org/openremote/manager/rules/RulesService.java
> +                container
I think a `LOG NODE` should exist always so the need to read `OR_DEV_MODE` goes away doesn't it?

2025-01-21 11:10 UTC, richturner commented on manager/src/main/java/org/openremote/manager/rules/flow/FlowResourceImpl.java
> +        if(MapAccess.getBoolean(container.getConfig(), "OR_DEV_MODE",false)){
It needs to use the Logger from the RulesetDeployment as each rule has its' own logger, you should be able to get hold of this during building

2025-01-21 17:04 UTC, pankalog commented on ui/component/or-rules/src/flow-viewer/components/internal-picker.ts
> +                return this.getNumberInput(0, 365);
@MartinaeyNL it now uses `this.getNumberInput(undefined, undefined);` which uses `ifDefined` to set those limits, practically giving the same as `this.numberInput` from `master`.

2025-01-22 17:30 UTC, richturner requested changes
Seem to be quite a few changes that are unused and also some changes (styling) don't seem to relate to the original issue and no explanation of why they are needed.

2025-01-22 17:30 UTC, richturner commented on manager/src/main/java/org/openremote/manager/rules/flow/NodeExecutionRequestInfo.java
> +    }
I don't see much value in this apart from avoiding code reuse, see suggestion for SUM_PROCESSOR

2025-01-22 17:30 UTC, richturner commented on manager/src/main/java/org/openremote/manager/rules/flow/NodeExecutionRequestInfo.java
> +    public Logger getLog(){return LOG;}
We like spaces and new lines in our code base, but anyway this can be removed just make the `LOG` field `protected`.
```
    public Logger getLog() {
    return LOG;}
```

2025-01-22 17:30 UTC, richturner commented on model/src/main/java/org/openremote/model/rules/flow/FlowResource.java
> +    boolean getDoesMatch(@BeanParam RequestParams requestParams, @PathParam("from") NodeDataType fromType, @PathParam("to") NodeDataType toType);
Do we need to move this to the backend? What is the benefit for the added load on the backend?

2025-01-22 17:30 UTC, richturner commented on ui/app/shared/locales/en/or.json
Will need to move keys in all language files not just this one

2025-01-22 17:30 UTC, richturner commented on ui/component/or-rules/src/flow-viewer/components/flow-node-socket.ts
> +        return socketType.replace("_array", "")
This looks hacky

2025-01-22 17:30 UTC, richturner commented on ui/component/or-rules/src/flow-viewer/components/flow-node.ts
> +                const style = isNewLine ? "flex-basis: 100%;" : "";
What is this styling and newline logic?

2025-01-22 17:30 UTC, richturner commented on model/src/main/java/org/openremote/model/rules/flow/NodeDataType.java
> +    NUMBER_ATTRIBUTE,
No usages of this

2025-01-22 17:30 UTC, richturner commented on model/src/main/java/org/openremote/model/rules/flow/NodeDataType.java
> +    NUMBER_ARRAY,
I don't see what value this is adding as it only seems to be used for matching logic

2025-01-22 17:30 UTC, richturner commented on model/src/main/java/org/openremote/model/rules/flow/Node.java
> +    private int priority = 999;
Where is this used?

2025-01-22 17:30 UTC, richturner commented on model/src/main/java/org/openremote/model/rules/flow/Node.java
> +
Where is this used?

2025-01-24 10:24 UTC, pankalog commented on manager/src/main/java/org/openremote/manager/rules/flow/NodeExecutionRequestInfo.java
> +    }
Since `getValueFromInput` does not really support retrieving the values from multiple different previous nodes, I created this method to simplify that process. This method just figures out which nodes are connected to the node we are currently on, and then requests the execution of all nodes. It then returns the result as an array of Objects. This does most of the heavy lifting for allowing a socket to request the results from multiple different inputs to that socket.

2025-01-24 10:27 UTC, pankalog commented on model/src/main/java/org/openremote/model/datapoint/query/AssetDatapointTimestampQuery.java
> +    }
Okay, this is the first time I was working with TimescaleDB and from what I read, if I used that `nearest_row` query first, it should for sure use the indices in the table.

2025-01-24 10:29 UTC, pankalog commented on model/src/main/java/org/openremote/model/rules/flow/FlowResource.java
> +    boolean getDoesMatch(@BeanParam RequestParams requestParams, @PathParam("from") NodeDataType fromType, @PathParam("to") NodeDataType toType);
This used to be in `socket.type.matcher.ts`, it had a TODO of moving this to the backend, and I thought it was a good change, since we're enforcing the rules of matching sockets to other sockets by moving it to the backend. I also feel that this gives a bit more certainty, since the other version just used a hard-coded JSON object for the matching.

2025-01-24 10:31 UTC, pankalog commented on model/src/main/java/org/openremote/model/rules/flow/Node.java
> +    private int priority = 999;
@pierrekil asked me to make it so that the processor blocks are displayed on the UI in a specific order, so that priority variable is what we use on all processors in the frontend to sort the processors in the desired order.

2025-01-24 10:37 UTC, pankalog commented on model/src/main/java/org/openremote/model/rules/flow/NodeDataType.java
> +    NUMBER_ARRAY,
I couldn't really think of another way of allowing arrays of objects without seriously affecting the rest of the codebase. I think it makes sense, since it is a new data type that is supported, and has different properties than the rest of the data types. Do you have any other ideas?

2025-01-24 10:37 UTC, pankalog commented on ui/app/shared/locales/en/or.json
Is there a fast way to do that?

2025-01-24 10:46 UTC, pankalog commented on ui/component/or-rules/src/flow-viewer/components/flow-node-socket.ts
> +        return socketType.replace("_array", "")
This is only used for properly coloring, naming the socket, and properly defining the input type of the socket that is created.  So for example the `SUM_PROCESSOR`, even if it has `NUMBER_ARRAY` as an input socket, it should not accept `NUMBER_ARRAY` inputs, but it should accept `NUMBER` inputs. The code of the processor itself collects the results of the connected input nodes and creates the number array, and then serves a number as output.

2025-01-24 10:49 UTC, pankalog commented on ui/component/or-rules/src/flow-viewer/components/flow-node.ts
> +                const style = isNewLine ? "flex-basis: 100%;" : "";
This is part of the formatting changes I have made for node internals, the `HISTORIC_VALUE` block contains 3 inputs that should be formatted correctly. `NodeInternalBreakType` deines `NEW_LINE` and `SPACER`, which is used to either break the next element to a new line in the UI, or add a spacer (keep everything in the same line).

2025-01-24 10:52 UTC, pankalog commented on ui/component/or-rules/src/flow-viewer/components/internal-picker.ts
> +                return this.getNumberInput(0, 365);
If I simply use the previous implementation of `getNumberInput` the number field is way too wide (Look at the NUMBER input block). Since people won't be using that big of a number when defining a period of time from/since now, I modified `NumberInput` to allow a variable amount of width depending on the situation. I believe that the biggest amount of time that they may reasonably require is 365, and it doesn't limit the actual number input, just the size of the number field.

2025-01-27 14:54 UTC, richturner commented on model/src/main/java/org/openremote/model/datapoint/query/AssetDatapointTimestampQuery.java
> +    }
Good to be thinking about indexes, you can use explain to see if indexes are being utilised for a given query and you shouldn't need a CTE here.

2025-01-27 18:18 UTC, richturner requested changes

2025-01-28 14:33 UTC, richturner requested changes
Looking good, just need to update al or.json language files as you've moved flow strings and add additional testing.

2025-01-28 14:33 UTC, richturner commented on ui/app/shared/locales/en/or.json
Not that I can think of, just replicate what you have done for en

2025-01-28 14:33 UTC, richturner commented on test/src/test/groovy/org/openremote/test/rules/residence/FlowRulesTest.groovy
> +    def "Test HISTORIC_VALUE and SUM blocks"() {
Would be good to have other added functionality covered in test

2025-01-29 12:16 UTC, richturner requested changes
Just some minor points

2025-01-29 12:16 UTC, richturner commented on test/src/test/groovy/org/openremote/test/rules/residence/FlowRulesTest.groovy
> +    def "Test newly-added blocks"() {
newly added is a time sensitive concept so please expand

2025-01-29 12:16 UTC, richturner commented on test/src/test/resources/org/openremote/test/rules/HistoricAndNewProcessorTest.flow
Don't use New in file names, is it still new in 6 months?

Just use the same name you have given the ruleset in the test `HistoricValueAndProcessors`

2025-01-29 12:16 UTC, richturner commented on test/src/test/groovy/org/openremote/test/rules/residence/FlowRulesTest.groovy
> +        when: "I add the test"
```suggestion
        when: "A flow rules is added"
```

2025-01-29 12:16 UTC, richturner commented on test/src/test/groovy/org/openremote/test/rules/residence/FlowRulesTest.groovy
>          and: "After the rule runs, the value the attribute had at that timestamp is written to the output attribute"
```suggestion
        and: "The rule runs and the various attributes are updated accordingly"
```

2025-01-29 15:17 UTC, richturner approved these changes

2025-01-29 16:05 UTC, merged