Migrate OpenRemote to Java 21 LTS
openremote/openremote pull request #1526
Opened 2024-12-07 15:54 UTC by pankalog

Test for migrating to Java 21, with various version changes to vulnerable dependencies.

Required some refactoring to `CalendarEvent`, due to `ical4j`'s move to `java.util` interfaces.

2024-12-09 10:24 UTC, wborn requested changes
The Docker base images also need to be updated for this to work:

https://github.com/search?q=repo%3Aopenremote%2Fopenremote%20openjdk-17&type=code

2024-12-09 10:42 UTC, wborn commented on gradle.properties
> +spockVersion = 2.4-M4-groovy-4.0
Is there a reason for using a milestone release instead of the latest stable release (2.3-groovy-4.0)?

2024-12-24 16:39 UTC, pankalog commented
@wborn if this is good, I'll also do some refactoring in the docs repository to reflect the changes (and also any references to Java 17).

2025-01-06 09:38 UTC, wborn requested changes

2025-01-06 09:38 UTC, wborn commented on gradlew
> +# Copyright © 2015-2021 the original authors.
There's still an encoding issue here.

2025-01-06 09:38 UTC, wborn commented on gradlew
> +#         * various built-in commands including «command», «set», and «ulimit».
There's still an encoding issue here.

2025-01-06 16:34 UTC, wborn commented on gradlew
> +# Copyright © 2015-2021 the original authors.
I cloned your branch locally and it looks fine so it is probably just some GitHub issue.

2025-01-06 16:34 UTC, wborn commented on gradlew
> +#         * various built-in commands including «command», «set», and «ulimit».
I cloned your branch locally and it looks fine so it is probably just some GitHub issue.

2025-01-13 08:16 UTC, pankalog commented
@wborn not sure how you want to proceed, let me know if I need to do anything else!

2025-01-17 09:28 UTC, wborn approved these changes

2025-01-17 09:30 UTC, wborn commented
There's also some documentation that needs to be updated when this gets merged:

https://docs.openremote.io/docs/developer-guide/preparing-the-environment/#development-tooling

2025-01-17 09:40 UTC, pankalog commented
@richturner @wborn I just thought that there is the potential of potential issues with JVM compatibility of the maven packages that are released. So after this is merged, it may require a new release for it to be used in all custom projects. Am I wrong?

2025-01-17 13:32 UTC, wborn requested changes
I just ran found this Gradle config that also needs to be updated:

https://github.com/openremote/openremote/blob/d932073abd251c8fc969038fccfba9ea07e130e2/project.gradle#L382-L385

This also exists in custom projects.

2025-01-18 18:55 UTC, pankalog commented
> I just found this Gradle config that also needs to be updated:
> 
> https://github.com/openremote/openremote/blob/d932073abd251c8fc969038fccfba9ea07e130e2/project.gradle#L382-L385
> 
> This also exists in custom projects.


@wborn This was done on the first commit of this branch, and it's still in the branch: https://github.com/openremote/openremote/blob/148282ab0ce85ba7c4469b914d879148ad4a0bb9/project.gradle#L382-L385

2025-01-23 09:50 UTC, wborn commented
> This was done on the first commit of this branch

Yes I see it now! :nerd_face:

2025-01-23 10:30 UTC, wborn submitted a review, later dismissed
I just gave it a brief test and it seems to work well. :+1: 
Maybe @richturner can also have a look?

2025-01-24 12:08 UTC, MartinaeyNL commented on gradle.properties
> +keycloakVersion = 25.0.3
Is this compatible with our Keycloak version 23 image?

2025-01-24 12:08 UTC, MartinaeyNL commented on gradle.properties
> +org.gradle.jvmargs=-Xms256m -Xmx2048m
What's this increase in memory for?

2025-01-27 11:36 UTC, richturner commented on gradle.properties
> +org.gradle.jvmargs=-Xms256m -Xmx2048m
Max heap size increase for build is ok

2025-02-10 16:14 UTC, richturner commented on project.gradle
> +    maven { url 'https://jitpack.io' }
These are needed by a couple of the dependencies which don't publish to central, have updated to use `url =`

2025-02-10 16:19 UTC, wborn approved these changes
LGTM now! :+1:

2025-02-10 16:28 UTC, merged