Fix for rules with 2 LHS conditions not properly being able to retrigger an action when only one condition becomes false and true again
openremote/openremote pull request #1546
Opened 2024-12-16 14:48 UTC by dominiquekleeven

Draft Pull Request for #798 

**Root cause:**
When a RuleSet contains multiple LHS conditions that have an AND relationship, the rule action would fail to re-trigger under certain circumstances. This was due to how `RuleConditionState` uses `previouslyMatchedAssetStates` to prevent re triggers.

**Scenario that failed:**
1. RuleSet has two LHS conditions (A AND B)
2. Both conditions evaluate to true → Action triggers (working as expected)
3. Condition A becomes false
4. Condition A becomes true again
5. Action fails to trigger because Condition B is still considered a non-match because it has `previouslyMatchedAssetStates`

**Current Fix:**
Modified `RuleState` to properly handle this case by:
1. Checking if any condition has new matches
2. Verifying if all other conditions either:
   - Have previous matches stored
   - Are currently matching

--

Draft pull request for now since I am still unsure about a couple things and a test case should be added for the issue scenario.

2025-01-10 10:48 UTC, dominiquekleeven commented
Added a test case for multi LHS conditions, manually tested in demo setup as well, issue seems to be resolved.

@richturner Unsure if this the ideal approach to resolving the issue. 

I've added logic to the updateMatches method in the RuleState class so that when a condition group (with multiple conditions) fails to match, the previouslyMatchedAssetStates is cleared for each of those conditions, provided that at least one of the conditions has no previouslyMatchedAssetStates.

2025-01-13 19:01 UTC, dominiquekleeven commented
Potentially also fixes #964 will confirm this later this week as time permits.

2025-01-26 21:24 UTC, richturner requested changes
Just a minor adjustment to improve performance a little but this solution seems sensible and I gave up trying to think of an alternative without major changes.

2025-01-26 21:24 UTC, richturner commented on manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java
> +                            .anyMatch(ruleConditionState -> ruleConditionState.previouslyMatchedAssetStates.isEmpty());
The `anyConditionHasNoPreviousMatches` check could be moved into the iteration at line 482 and then this if becomes:

`if (!groupMatches && anyConditionHasNoPreviousMatches && ruleConditionGroup.getItems().size() > 1)`

2025-01-30 10:12 UTC, dominiquekleeven commented on manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java
> +                            .anyMatch(ruleConditionState -> ruleConditionState.previouslyMatchedAssetStates.isEmpty());
Thanks for the review.

I am a bit unsure how to properly move the `anyConditionHasNoPreviousMatches` assignment into the existing stream at line 482, `.allMatches` is a short circuit operation, so it won't properly check all conditionStates for empty previouslyMatchedAssetStates, if I do the assignment inside of the `.map`.

2025-01-31 10:30 UTC, richturner commented on manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java
> +                            .anyMatch(ruleConditionState -> ruleConditionState.previouslyMatchedAssetStates.isEmpty());
Yes you're right I was a bit hasty in thinking the `.allMatches()` had to be true but it's the opposite!

2025-01-31 10:32 UTC, richturner approved these changes

2025-02-03 09:27 UTC, merged