Updated username regex pattern based on Keycloak validation
openremote/openremote pull request #1550
Opened 2024-12-18 13:58 UTC by MartinaeyNL

Currently, the username field only accepts regular A-Z, 0-9 and a few special characters.
This was causing issues in Keycloak configurations where email is used as a unique identifier.

I've updated the regex pattern to allow special characters, and be in line with Keycloak their validation.

According to the [Keycloak changelog](https://www.keycloak.org/docs/latest/upgrading/#default-validations), they apply two validators by default;
`username-prohibited-characters`, and `up-username-not-idn-homograph`. See the documentation on these validators [here](https://www.keycloak.org/docs/26.0.7/server_admin/#built-in-validators).

I've copied these regex patterns from the Keycloak open source codebase, and combined them myself.
The sources can be found in [UsernameProhibitedCharactersValidator.java](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/userprofile/validator/UsernameProhibitedCharactersValidator.java#L44) and [Validation.java](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/validation/Validation.java#L37) respectively.

The exact list of supported and unsupported characters can be found [here](https://github.com/keycloak/keycloak/blob/main/services/src/test/java/org/keycloak/userprofile/validator/UsernameProhibitedCharactersValidatorTest.java).

2024-12-19 10:13 UTC, richturner requested changes
Hey @MartinaeyNL have you tested this regex after unescaping and testing at:

https://www.regexplanet.com/advanced/java/index.html

I couldn't get a password with any symbols to match

2025-01-07 08:27 UTC, richturner commented
Any update on this?

2025-01-07 08:31 UTC, MartinaeyNL commented
Thanks for the heads-up! I haven't worked on this since the holidays, so I'll pick this up.

2025-01-08 20:58 UTC, richturner commented
Should we not have regex check on frontend also?

2025-01-09 14:09 UTC, MartinaeyNL commented
Thanks! I unfortunately didn't manage to get the complex regexp working in JavaScript,
so I manually added the special characters instead.

2025-01-20 11:23 UTC, richturner commented on ui/app/manager/src/pages/page-users.ts
> +                                  .value="${user.username}"
Was the autocomplete attribute removed on purpose?

2025-01-20 12:19 UTC, MartinaeyNL commented on ui/app/manager/src/pages/page-users.ts
> +                                  .value="${user.username}"
Probably a result of merging with the latest changes in #1566.
So yes, the `autocomplete` attribute should be set to `false`, I'll commit that right away.

2025-01-20 12:26 UTC, MartinaeyNL commented
See my comments. Feel free to review again! 👍

2025-01-20 12:26 UTC, richturner approved these changes

2025-01-20 12:46 UTC, merged