Added limit options on datapoint CSV export
openremote/openremote pull request #1558
Opened 2024-12-20 10:06 UTC by MartinaeyNL

Closes #1473 

Added support for the `OR_DATA_POINTS_EXPORT_LIMIT` environment variable,
to refuse CSV exports above the threshold. By default, this limit is set to 1 million data points.

2024-12-20 10:31 UTC, MartinaeyNL commented
Converted to draft as I'm working on test coverage for the PR.

2024-12-20 16:43 UTC, MartinaeyNL commented
Ready for review! 👍 

_(I won't assign a reviewer for now, because of the holidays)_

2025-01-07 10:24 UTC, wborn requested changes

2025-01-07 10:24 UTC, wborn commented on manager/src/main/java/org/openremote/manager/datapoint/AssetDatapointService.java
> +            StringBuilder sb = new StringBuilder(String.format("copy ("))
Redundant String formatting:

```suggestion
            StringBuilder sb = new StringBuilder("copy (")
```

2025-01-07 10:25 UTC, wborn approved these changes

2025-01-07 10:37 UTC, merged