Enhancement/gateway widget offline feedback
openremote/openremote pull request #1564
Opened 2024-12-23 10:44 UTC by Hackerberg43

With a widget, you could try to start a tunnel trough a gateway that is not online. This returned the generic snackbar error "An error has occured", providing no feedback why.

Added an http request to get the actual gatewayStatus and gray out the start button if returned status isn't "CONNECTED"

--> Must still be tested on a live master-gateway setup

2025-01-09 10:07 UTC, MartinaeyNL requested changes

2025-01-09 18:07 UTC, Hackerberg43 commented on ui/component/or-dashboard-builder/src/widgets/gateway-widget.ts
> +        this._getGatewayStatus(tunnelInfo)
Right, thanks for the valuable explanation, I had a bit of a blind spot with some of the functions but you have led me to the lit lifecycle documentation o/

2025-01-13 12:17 UTC, Hackerberg43 commented on ui/component/or-dashboard-builder/src/widgets/gateway-widget.ts
> +        this._getGatewayStatus(tunnelInfo)
the request has been added to firstUpdated() and refreshContent, the latter was necessary to let it also update when a cyclic update period is set. Should have resolved all comments now.

2025-01-23 15:19 UTC, MartinaeyNL approved these changes

2025-01-23 15:27 UTC, merged