Add password policy to account page
openremote/openremote pull request #1565
Opened 2024-12-23 15:21 UTC by Hackerberg43

- In continuation of #1524 , copied @MartinaeyNL his code and applied it to the account page aswell.
- Fixed that snackbar on account page didn't correctly display password update result.

Points of discussion:
- I've simply copied the _getPasswordPolicyTemplate function, so there is duplicate code now.
Might want to create a component wrapping the password change fields + policy ?

- While working on this, realized that there is no "current password" field. Is this on purpose ? Seems like a security risk regarding devices with an open session left unguarded. Wouldnt allowing only a forced password reset on the user page and requiring "current password" on the account page make sense?

2025-01-06 17:55 UTC, DonWillems commented
> * While working on this, realized that there is no "current password" field. Is this on purpose ? Seems like a security risk regarding devices with an open session left unguarded. Wouldnt allowing only a forced password reset on the user page and requiring "current password" on the account page make sense?

Yes that makes sense, I will add it to our backlog: https://github.com/openremote/openremote/issues/1570

2025-01-09 10:15 UTC, MartinaeyNL requested changes

2025-01-09 10:15 UTC, MartinaeyNL commented on ui/app/manager/src/pages/page-account.ts
> +        this._getPasswordPolicy();
`render()` is a Lit function that gets called often during every state update,
Expensive functions like this `_getPasswordPolicy()` HTTP request should happen only once.
I would place this in a `connectedCallback()` function, which gets called before initial page render.
```typescript
connectedCallback() {
    super.connectedCallback();
    this._getPasswordPolicy().then(policy => {
        this._passwordPolicy = policy;
    })
}
```

2025-01-09 10:15 UTC, MartinaeyNL commented on ui/app/manager/src/pages/page-account.ts
> +        this._passwordPolicy = realmResponse.data.passwordPolicy;
I would just return the async function here;
```typescript
return await manager.rest.api.RealmResource.get(manager.getRealm());
```
Catching errors, and updating local state, should be handled outside of this function.

2025-01-13 14:43 UTC, Hackerberg43 commented on ui/app/manager/src/pages/page-account.ts
> +        this._passwordPolicy = realmResponse.data.passwordPolicy;
I've tried this but it resulted in a type mismatch I couldn't get around. Also, I found no other places where this is actually done in the code. So I kept the function in line with similar functions .. ?

2025-01-21 10:28 UTC, MartinaeyNL approved these changes
LGTM

2025-01-21 10:28 UTC, merged