Feature/realm role input
openremote/openremote pull request #750
Opened 2022-06-27 11:17 UTC by robin-dekkers

2022-06-27 12:18 UTC, DonWillems requested changes
Looks good. Only remarks directly related to this PR would be that the text in the button should be '# Assets' instead of 'linked assets'. It does not show the selected assets count anymore, which it should. ({{number}} parameter in translations)

Remarks sort of related, can be picked up in separate PR if they do not fit:
- Now that we have 'Realm roles', maybe the other roles should be named 'Manager roles'
- There is no space after the comma of each selected role (", ") in the multiselect field, which would be nicer.
- The permissions (under the roles select) are alphabetically horizontal instead of vertical. Vertical they would be nicely split in read: and write:...

2022-06-28 09:52 UTC, DonWillems submitted a review, later dismissed

2022-06-28 13:54 UTC, richturner commented on ui/app/manager/src/pages/page-users.ts
> +                                                user.realmRoles = this._realmRoles.filter(cr => roleNames.some(name => cr.name === name)).map(r => {
This looks like it will remove the excluded roles from the user which it should not @DonWillems do I need to resolve this ready for tomorrow?

2022-06-28 15:33 UTC, richturner submitted a review, later dismissed

2022-06-28 15:41 UTC, richturner commented on ui/app/manager/src/pages/page-users.ts
> +                                                user.realmRoles = this._realmRoles.filter(cr => roleNames.some(name => cr.name === name)).map(r => {
Resolved now

2022-06-28 15:41 UTC, richturner approved these changes

2022-06-28 15:42 UTC, merged